// <auto-generated />
using System;
using PeixeNaRede.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace PeixeNaRede.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20240607221617_Global")]
    partial class Global
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Captura", b =>
                {
                    b.Property<int>("CdCaptura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CdCaptura"));

                    b.Property<int>("CdEspecie")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("CdPescaria")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("DsFoto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<float>("DsPeso")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<int>("DsQuantidade")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("CdCaptura");

                    b.HasIndex("CdEspecie");

                    b.HasIndex("CdPescaria");

                    b.ToTable("Captura");
                });

            modelBuilder.Entity("Encontro", b =>
                {
                    b.Property<int>("CdEncontro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CdEncontro"));

                    b.Property<string>("DsLocal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("DsStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<DateTime>("DtEncontro")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("CdEncontro");

                    b.ToTable("Encontro");
                });

            modelBuilder.Entity("EncontroUsuario", b =>
                {
                    b.Property<int>("CdUsuario")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("CdEncontro")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("CdUsuario", "CdEncontro");

                    b.HasIndex("CdEncontro");

                    b.ToTable("EncontrosUsuarios");
                });

            modelBuilder.Entity("Especie", b =>
                {
                    b.Property<int>("CdEspecie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CdEspecie"));

                    b.Property<string>("DsDescricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("DsFoto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("NmCientifico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("NmPopular")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("CdEspecie");

                    b.ToTable("Especie");
                });

            modelBuilder.Entity("Oferta", b =>
                {
                    b.Property<int>("CdOferta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CdOferta"));

                    b.Property<int>("CdEncontro")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("DsEspecie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<int>("DsQuantidade")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("DsStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<float>("VlPreco")
                        .HasColumnType("BINARY_FLOAT");

                    b.HasKey("CdOferta");

                    b.HasIndex("CdEncontro");

                    b.ToTable("Oferta");
                });

            modelBuilder.Entity("Pescaria", b =>
                {
                    b.Property<int>("CdPescaria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CdPescaria"));

                    b.Property<string>("DsCondicoesClimaticas")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DsDetalhes")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DsLocalizacao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)");

                    b.Property<string>("DsMetodoPesca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<DateTime>("DtPescaria")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("TpPesca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.HasKey("CdPescaria");

                    b.ToTable("Pescaria");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Property<int>("CdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CdUsuario"));

                    b.Property<int>("CdPescaria")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("DsEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("DsFotoPerfil")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("DsLocalizacao")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)");

                    b.Property<string>("DsSenha")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("DsTipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<string>("NmUsuario")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.HasKey("CdUsuario");

                    b.HasIndex("CdPescaria");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Captura", b =>
                {
                    b.HasOne("Especie", "Especie")
                        .WithMany("Capturas")
                        .HasForeignKey("CdEspecie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pescaria", "Pescaria")
                        .WithMany("Capturas")
                        .HasForeignKey("CdPescaria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especie");

                    b.Navigation("Pescaria");
                });

            modelBuilder.Entity("EncontroUsuario", b =>
                {
                    b.HasOne("Encontro", "Encontro")
                        .WithMany("EncontrosUsuarios")
                        .HasForeignKey("CdEncontro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Usuario", "Usuario")
                        .WithMany("EncontrosUsuarios")
                        .HasForeignKey("CdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encontro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Oferta", b =>
                {
                    b.HasOne("Encontro", "Encontro")
                        .WithMany("Ofertas")
                        .HasForeignKey("CdEncontro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encontro");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.HasOne("Pescaria", "Pescaria")
                        .WithMany("Usuarios")
                        .HasForeignKey("CdPescaria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pescaria");
                });

            modelBuilder.Entity("Encontro", b =>
                {
                    b.Navigation("EncontrosUsuarios");

                    b.Navigation("Ofertas");
                });

            modelBuilder.Entity("Especie", b =>
                {
                    b.Navigation("Capturas");
                });

            modelBuilder.Entity("Pescaria", b =>
                {
                    b.Navigation("Capturas");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Navigation("EncontrosUsuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
